// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAj-sel3a_FBlKXTUv-E5-z69Pscfmvi_s",
    appId: "1:202620355081:android:658c9e49aace3150092ed8",
    messagingSenderId: "202620355081",
    projectId: "readverse-9da4a",
    storageBucket: "readverse-9da4a.firebasestorage.app",
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyAAbI1fyyf8Q7BDnhtMXiRzQQptYIGG1UI',
  //   appId: 'your-ios-app-id',
  //   messagingSenderId: 'your-sender-id',
  //   projectId: 'your-project-id',
  //   storageBucket: 'your-storage-bucket',
  //   iosClientId: 'your-ios-client-id',
  //   iosBundleId: 'com.example.readverse',
  // );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAj-sel3a_FBlKXTUv-E5-z69Pscfmvi_s",
      authDomain: "readverse-9da4a.firebaseapp.com",
      projectId: "readverse-9da4a",
      storageBucket: "readverse-9da4a.firebasestorage.app",
      messagingSenderId: "202620355081",
      appId: "1:202620355081:web:3b6256a9b86e3242092ed8",
      measurementId: "G-94B9ZXPSEH");
}
